### ISSUE TITLE
你好，项目运行

### ISSUE THREAD

**Issue by catlat** [BitBrewing/EInvoiceXml2Pdf#1]
你好，非常感谢分享，刚好有一个xml发票转pdf的需要，但是不熟悉C#代码项目，看资料搞了半天没有跑起来，想请教下这个项目如何正确运行起来，或者有没有可运行的打包文件分享，再次感谢！

**Comment by BitBrewing** [comment]
需要使用vs2022或者vscode来打开

**Comment by catlat** [comment]
好嘞，谢谢！

**Comment by helloint** [comment]
非常好的项目👍
我是前端工程师，打开工程也很迷茫，不知道怎么用。摸索了下，懂了。为了方便后来的人，留个Fork https://github.com/helloint/EInvoiceXml2Pdf ，支持批量修改，添加了readme。
